### ISSUE TITLE
Fantastic JOB

### ISSUE THREAD

**Issue by wizard699** [aclissold/the-oakland-post#47]
Only a word: FANTASTIC!!!
Many compliments for your job.
I'm at start with swift coding .... but, it's possibile to have some tips to extract and use your Info page in other apps?  If I copy class and View in a app coded with Object C, there are a lot of error.
Which are dependencies for Info page?

Thanks

**Comment by rome111** [comment]
Great Job! I'm new to coding but this is one of the best open source apps I've come across. Could you give me some advice on how to add multiple rss feeds to the app?

Thanks.

**Comment by aclissold** [comment]
Nice!! Thanks! I guess I'll use this issue as a general discussion board :stuck_out_tongue:

That's pretty vague, but here's a head start… let's say you want to use your own custom RSS feeds in the Sections view, like Hacker News.

![Hacker News](https://cloud.githubusercontent.com/assets/4397642/7784960/20c64954-0148-11e5-859b-29efef056a07.png)

 in `Main.storyboard`, click on the web view for `PostViewController` and set it to "Scale Pages To Fit." I have this disabled since the content of my RSS feed is just text that I don't want people to zoom into.

![step 1](https://cloud.githubusercontent.com/assets/4397642/7784964/ad394c24-0148-11e5-9984-7124b9944fed.png)
![step 2](https://cloud.githubusercontent.com/assets/4397642/7784965/af4bc37a-0148-11e5-9707-4800efc83a3f.png)

Then you'll wanted to modify `FeedParser.swift` because I'm doing stuff that's only relevant to my RSS feed in there as well.

**Before:**
``` swift
return NSURL(string: "\(baseURL)&o=\(offset)&l=\(length)&f=rss")!`
```

**After:**
``` swift
return NSURL(string: baseURL)!`.
```

Similarly, in `PostViewController.swift` I'm forcing the mobile site. You can disable this by commenting it out.

``` swift
// URL = URL.stringByReplacingOccurrencesOfString("//www", withString: "//m")
```

Finally, add Hacker News to `SectionsViewController.swift` by adding its name to the array of section titles and adding its URL to the array of URLs:

``` swift
let titles = ["News", "Life", "Sports", "Arts & Entertainment", "Opinion", "Satire", "Hacker News"]
let baseURLs = [
    "News": "\(prefix)news,news/*",
    "Life": "\(prefix)life,life/*",
    "Sports": "\(prefix)sports,sports/*",
    "Arts & Entertainment": "\(prefix)arts_and_entertainment,arts_and_entertainment/*",
    "Opinion": "\(prefix)opinion,opinion/*",
    "Satire": "\(prefix)satire,satire/*",
    "Hacker News": "https://news.ycombinator.com/rss"
]
```

This will break the other sections though.
